### ISSUE TITLE
本地调试报405错误是什么原因呢

### ISSUE THREAD

**Issue by xiaoshan100** [TCloudBase/WXSEVER-SMS#2]
![image](https://user-images.githubusercontent.com/22276440/105173831-8ca9f700-5b5c-11eb-9576-fc34422f6d72.png),
项目目录如下
![image](https://user-images.githubusercontent.com/22276440/105173930-b531f100-5b5c-11eb-8ec5-eebd08651deb.png)
配置如下
![image](https://user-images.githubusercontent.com/22276440/105174022-ddb9eb00-5b5c-11eb-9ebf-cd360bc220bc.png)

**Comment by wxcloudbase** [comment]
JS本地调试问题
